# The name of the workflow
name: npm-bats-sample
# The name for workflow runs: "<username> is learning GitHub Actions"
run-name: ${{ github.actor }} is learning GitHub Actions
# Trigger this workflow manually by the web interface or web API
on:
  workflow_dispatch:

jobs:
  # Job definition
  check-bats-version:
    # Run the job on the latest version of an Ubuntu Linux runner
    runs-on: ubuntu-latest
    steps:
      # Run `v3` of `actions/checkout`: checkout a repository onto
      # the runner
      - uses: actions/checkout@v3
      # Run `v3` of `actions/setup-nodes`: install Node.js with v14
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      # Run command: Install `bats` by using `npm`
      - run: npm install -g bats
    # Run command: `bats -v`
      - run: bats -v

